### PR TITLE
Complete refactoring

### PR DESCRIPTION
**Pull request by leogr**

### CODE REVIEW

**Comment by leodido** [comment]
Thanks @leogr.

Only one last thing we could do before merging within the develop is to dispatch events for chip addition and/or deletion.

Something similar or equal to this [PR](https://github.com/fabbricadigitale/paper-chip/pull/57).

@alelb would you provide this feature?

**Comment by leogr** [comment]
Note also that `paper-chip-input` doesn't have a min height anymore, so
maybe some side-effect has been introduced. I had toughs about that but I
had not enough time to double check all use cases.




Il 13 ott 2017 2:43 PM, "Leonardo Di Donato" <notifications@github.com> ha
scritto:

Thanks @leogr <https://github.com/leogr>.

Only one last thing we could do before merging within the develop is to
dispatch events for chip addition and/or deletion.

Something similar or equal to this PR
<https://github.com/fabbricadigitale/paper-chip/pull/57>.

@alelb <https://github.com/alelb> would you provide this feature?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fabbricadigitale/paper-chip/pull/58#issuecomment-336441902>,
or mute the thread

**Comment by leogr** [comment]
Hey @alelb , I've seen this PR fixes a lot of side issues you closed. 
Did you check what's missing? Or can we merge?

**Comment by alelb** [comment]
@leogr the refactoring it's completed. We have to add demo and docs to show the new supported feature.
Other features included in 0.12 milestone can be moved to the next milestone.

**Comment by leogr** [comment]
LGTM.
Waiting for @leodido 's review, then I think we can merge and release a new version.

**Comment by leogr** [comment]
Sorry, It was copy&paste. Actually, I agree to use the newer `dom-if`
syntax.

Il 08 gen 2018 1:19 PM, "Leonardo Di Donato" <notifications@github.com> ha
scritto:

**Pull request merged**
