### PR TITLE
New: Icon support for paper-chip-input

### PR DESCRIPTION
**Pull request by microDimensions**
This PR picks up where https://github.com/fabbricadigitale/paper-chip/pull/68 left, fixing the unit tests and the commit message.

### CODE REVIEW

**Comment by leogr** [comment]
Hi @microDimensions @feuerste !
Thank you for this PR! 
Could you add an usage example in [demo](https://github.com/fabbricadigitale/paper-chip/blob/master/demo/index.html)?

**Comment by feuerste** [comment]
Hi @leogr I added two examples.

**Comment by leodido** [comment]
Code looks good. Thanks.

Anyway there are issues with tests setup. I think it is related to wct. Locally can you run them?

**Comment by leogr** [comment]
I can run them locally too. The issue with travis seems to be related to saucelabs. I'll investigate.

**Comment by leodido** [comment]
Anyway I merge it since the last commit (the one with travis/saucelabs issue can not interfer with tests...).

**Comment by feuerste** [comment]
Cool, thanks

**Pull request merged**
